name: (English) Server crash or Stacktrace
description: Report server crashes or scary stacktraces
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a crash or stacktrace here, please make sure you are on the latest version of Imanity WoolWars.
  - type: textarea
    attributes:
      label: Stack trace
      description: |
        We need all of the stack trace! Do not cut off parts of it. Please do not use attachments.
        If you prefer, you can use a paste site like https://paste.imanity.dev/.
      value: |
        ```
        paste your stack trace or a https://paste.imanity.dev/ link here!
        ```
      placeholder: Please don't remove the backticks; it makes your issue a lot harder to read!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps/models to reproduce (if known)
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue. Anything helps!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Imanity WoolWars version
      description: |
        Type `/ver WoolWars` in your server to get your current version.
        note that *LATEST* is not a version.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Spigot information
      description: |
        We need to know what spigot do you run with Imanity Woolwars.
        Please also provide the version using /ver command in the server.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Imanity WoolWars available from the resource page.
          required: true
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false
